name: testing

on:
  push:
    branches:
      - 'master'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - java_version: '17'

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Test with Gradle
        working-directory: freemarker-wrapper/
        run: ./gradlew test runtime

      - uses: actions/upload-artifact@v3
        with:
          name: "engine-wrapper_bundles"
          path: freemarker-wrapper/build/image

      - uses: actions/upload-artifact@v3
        with:
          name: "engine-wrapper_java-${{ matrix.java_version }}"
          path: freemarker-wrapper/build/libs

      - name: Test Results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'freemarker-wrapper/build/test-results/test/*.xml'
          fail_on_failure: true
          require_tests: true
          check_name: 'test results - java version: ${{ matrix.java_version }}'
